### ISSUE TITLE
kong.client.loadConsumer(UUID) throws error in custom js Plugin

### ISSUE THREAD

**Issue by spurj426** [Kong/kong-js-pdk#10]
It appears an RPC error is being thrown when trying to load a consumer by UUID.

We have verified our configurations and verified we are correctly passing in the UUID for our anonymous consumer, but continue to receive the following error:

**_[ERROR] rpc: #13 method "StepConsumer" not implemented_**

This is for a custom authorizer plugin.  Using references to the lua plugins for authorization, we are attempting to call **kong.client.loadConsumer(UUID)** inside the **access** method.

**Comment by fffonion** [comment]
Thanks for reporting this @spurj426 ! I have pushed a fix and it will be included in next release.
