### ISSUE TITLE
How to convert the response obtained from getRawBody() to a readable format ?

### ISSUE THREAD

**Issue by Aditya20kul** [Kong/kong-js-pdk#103]
Hi, i wanted to know if there was a way to decode the response obtained from getRawBody() into something that is readable, is there a seperate method for the same ?

**Comment by fffonion** [comment]
@Aditya20kul , getRawBody() returns the original body for response, you can use appropriate library to decode the
body, depending on the response body format.

**Comment by Aditya20kul** [comment]
Resolved
