### ISSUE TITLE
Unable to access environment variables from a plugin using `process.env`

### ISSUE THREAD

**Issue by oremut** [Kong/kong-js-pdk#13]
I am unable to access environment variables in my plugin using `process.env.<var_name>`. 

Logging `process.env` returns `table: 0x7f3bb3b346f0`, and `JSON.stringify(process.env` returns `{"SHLVL":"1","PWD":"/"}`.

`exec`ing into the Kong container and running `printenv` I can see the full list of environment variables that were set when Kong was deployed.

I was hoping to use environment variables to retrieve the password for an external Redis cache used by a plugin.

**Comment by oremut** [comment]
This isn't a problem with the js-pdk, so I'm closing this issue.
I found this issue: https://github.com/Kong/kong/issues/6149 where someone said
>Environment variables are cleared in the server worker processes by default — this means they are not visible either by Go or Lua plugins.
>
>But you can enable them explicitly using Nginx's env directive. For example, to expose the PATH variable, you can start kong with the following environment variable KONG_NGINX_MAIN_ENV=PATH, and Kong will inject the env directive in Nginx's main configuration section with the value PATH, and that variable should be visible from both Go and Lua.

Exposing the env variables using `KONG_NGINX_MAIN_ENV` made them visible to my js plugin.

In a lua plugin I wrote we were using environment variables, which is why I thought this was specific to the js pdk, but I was accessing them using the `resty.env` package, which must have been doing something special under the hood.

**Comment by sinalkar** [comment]
> Exposing the env variables using `KONG_NGINX_MAIN_ENV` made them visible to my js plugin.

@oremut  I tried same but not getting in process.env can you please share how to access

**Comment by oremut** [comment]
@sinalkar We are using Helm to deploy Kong in Kubernetes. In my `values.yaml` file I have `NGINX_MAIN_ENV: KONG_REDIS_AUTH_PASSWORD`. This gives me access to the env var named `KONG_REDIS_AUTH_PASSWORD` in my JS plugin. In the JS plugin I can access the env var with:
```
const process = require('process');

const password = process.env.KONG_REDIS_AUTH_PASSWORD;
```

If you need to expose more than one env variable you can do it like this in your values file:
```
NGINX_MAIN_ENV: KONG_REDIS_AUTH_PASSWORD; env ANOTHER_ENV_VAR; env YET_ANOTHER_ENV_VAR;
```
