### ISSUE TITLE
Modifying response body (no body_filter phase?)

### ISSUE THREAD

**Issue by nopol10** [Kong/kong-js-pdk#178]
Hi, I would like to check if it is currently possible to modify the response body with a Javascript plugin? The `body_filter` phase does not appear to be available and calling `getRawBody` in `response` does not work (in the docs it says it is a replacement for both `header_filter` and `body_filter` so I expected it to work there).

**Comment by fffonion** [comment]
Hi @nopol10 this is a known issue, we will fix in next release of kong (https://github.com/Kong/kong/issues/8622)

**Comment by hanshuebner** [comment]
Fix has been merged, closing.  Please re-open if you find this still to be a problem.
