### ISSUE TITLE
Add "Version" as named property in "GetPluginInfo"

### ISSUE THREAD

**Issue by thesheps** [Kong/kong-js-pdk#18]
Hey folks, great work here! We're encountering a problem when a `js-pdk` plugin is pushed out to data planes over the clustering connection. Not sure if this is a new problem or not, but the Data Planes each report the LUA error:

`Kong: Attempt to index field 'version' (a nil value)`

Digging into it I can see that the version of the plugin is not provided as part of the `GetPluginInfo` method. The following fix addresses this (I've got a branch ready if you're taking PRs!)

```
  async GetPluginInfo(name) {
    if (this.plugins[name] === undefined) {
      return Promise.reject(new PluginServerError(name + " not initialized"))
    }

    let plugin = this.plugins[name]

    return {
      Name: name,
      + Version: plugin.getVersion(),
      Phases: plugin.getPhases(),
      Priority: plugin.getPriority(),
      Schema: {
        name: name,
        fields: [{
          config: {
            type: "record",
            fields: plugin.getSchema(),
          }
        }],
      },
    }
  }
```

**Comment by fffonion** [comment]
Hi @thesheps , thanks for reporting this. PRs are definitely welcomed!

**Comment by thesheps** [comment]
Awesome, tag me in!
