### ISSUE TITLE
loadConsumer returns undefined

### ISSUE THREAD

**Issue by akira28** [Kong/kong-js-pdk#22]
I'm trying to retrieve a consumer both with `const consumer = await kong.client.loadConsumer('<uuid>');` and `const consumer = await kong.client.loadConsumer('<username>', true);` but `consumer` is always `undefined` (the uuid and username I'm trying are on db obviously).
What am I doing wrong?

**Comment by fffonion** [comment]
@akira28 Could you share the snippet the plugin so I can try to reproduce it on my side?

**Comment by akira28** [comment]
hi @fffonion I just found out that to work it needed the `ws_id` field.
Thing is I'm manually creating a consumer in my plugin as said here: https://github.com/Kong/kong-js-pdk/issues/21 and now I'm wondering how I determine the workspace without ugly queries. This is what I'm doing at the moment:

```
          let consumer = await kong.client.loadConsumer(`${user}`, true);
          if (!consumer) {
            const workspaces = await dbClient.query('SELECT id FROM workspaces;');
            const workspace = workspaces.rows[0];
            const id = uuidv4();
            await dbClient.query(`INSERT INTO consumers (id, username, ws_id) VALUES ('${uuidv4()}', '${user}', '${workspace.id}');`);
            consumer = await kong.client.loadConsumer(id);
          }
          await kong.client.authenticate(consumer);
```

**Comment by akira28** [comment]
as commented on #21 this is no longer needed
