### ISSUE TITLE
How to cache stuff?

### ISSUE THREAD

**Issue by akira28** [Kong/kong-js-pdk#23]
Is there a clean way to cache things with js plugins in Kong? Or I should use some npm package + redis or something?

Thanks

**Comment by fffonion** [comment]
@akira28 That's a good question. That depends on how you plan to use those cache.

With PDK, it goes through
network RPC and codec so it might not be worthy if producer/consumer are all from JS plugin side. For this use case,
you can cache it in local memory or something like redis.

If you plan to communicate JS plugin with otthers like Go or Lua plugin, you are looking at `kong.ctx.shared.get/set`.
It allows you to share data in the context of current request. But it doesn't persiste through different requests.
