### ISSUE TITLE
Issues running tests

### ISSUE THREAD

**Issue by akira28** [Kong/kong-js-pdk#24]
I'm trying to run tests for my plugin but I'm facing several issues that prevents having working tests:

- `ReferenceError: Headers is not defined` -> I had to polyfill Headers with `global.Headers = global.Headers || require('fetch-headers');`
- `function kong.response.error is not a valid PDK function` even if it works when I actually try the plugin, and is a documented function
- `.useURL('http://example.com')` throws a `Exceeded timeout of 5000 ms for a test` error

This is the test I'm trying to run:

```javascript
const { PluginTest, Request } = require('kong-pdk/plugin_test');
global.Headers = global.Headers || require('fetch-headers');

const plugin = require('./api-key-auth');

test('Set headers in response', async () => {
  const request = new Request();

  request
    .useURL('http://example.com')
    .useMethod('GET')
    .useHeaders({
      'x-api-key': 'abcde',
    })
    .useBody('OK');

  const pluginTest = new PluginTest(request);

  await pluginTest.Run(plugin, {});

  expect(pluginTest.response.status)
    .toBe(200);
});

```

**Comment by fffonion** [comment]
@akira28 Could you share the nodejs version and kong-js-pdk version you are using?

**Comment by akira28** [comment]
kong-js-pdk: 0.3.5
Node.js: v14.16.1
Jest: 27.0.6

I downloaded and executed the examples, and they worked as expected. I found out that with jest 26 the error `ReferenceError: Headers is not defined` is solved, but `function kong.response.error is not a valid PDK function` is still there

**Comment by fffonion** [comment]
@akira28 Thanks, I think it might be caused by jest 26 implictly depends on some module that provides the Headers class. Let me see if I can reproduce for the kong.response.error one.
