### ISSUE TITLE
Add some insights in the docs about the performance impact of using JS plugins

### ISSUE THREAD

**Issue by bovino** [Kong/kong-js-pdk#4]
Adding some insights in the docs (README and Kong official docs) about the expected impact on performance when using JS plugins would be nice even though they are slower than plugins written in Lua. 

Also adding some tips, recommendations or even samples on how to perform automated load testing for JS plugins would be very useful.

**Comment by fffonion** [comment]
We have just finished evaluation of the performance, the official documentaion will be posted shortly : )

**Comment by bovino** [comment]
This is excellent! Great job!

**Comment by fffonion** [comment]
The doc is now available at https://docs.konghq.com/gateway-oss/2.5.x/external-plugins/#performance-for-external-plugins. Closing this issue.
Thanks for bringing this up @bovino !

**Comment by bovino** [comment]
Great job! I will surely read it ASAP!
