### ISSUE TITLE
table.d.ts contains imports with missing types

### ISSUE THREAD

**Issue by adamboerema** [Kong/kong-js-pdk#9]
https://github.com/Kong/kong-js-pdk/blob/b27cd498acf7846b52835c0a404ce3c0ad04be0d/kong/table.d.ts#L4

It appears the generated TS type definitions from Lua are including a table definition that does not have have a matching import. Looking at the documentation I would assume that typescript doesn't have any use for the Lua tables but it is causing an issue with typescript transpilation.

**Comment by fffonion** [comment]
@adamboerema You are right, this definition was added by a automation script but it is indeed not used anywhere.
I will open a PR to remove it.

**Comment by adamboerema** [comment]
Appreciate it!
